### ISSUE TITLE
Infinite loop when building under Linux

### ISSUE THREAD

**Issue by nbkolchin** [jacereda/fina-forth#2]
```shell
$ make install
install -d `dirname obj/ans-report.help`
obj/fina help/glosgen.fs -e "newglos makeglos ans-report.fs writeglos obj/ans-report.help bye"
```

Last line executes forever. 

No such problem under MacOSX.

**Comment by jacereda** [comment]
Which compiler/version are you using?

**Comment by jacereda** [comment]
I've noticed a problem in the bootstrap code, can you try again?

I'm compiling without problems on NixOS with gcc 10.3.0.

**Comment by nbkolchin** [comment]
Archlinux 64-bit, gcc version 11.1.0 (GCC). Still hangs on glosgen.

Also, after starting 'fina' terminal must be resetted (reset) or no input is visible.

**Comment by nbkolchin** [comment]
And 32-bit build (scons arch=i386), hangs on

```
cat(["obj/kernel/i386-dict1.fs"], ["sys/core.fs", "sys/defer.fs", "sys/core2.fs", "sys/throwmsg.fs", "sys/based.fs", "sys/source.fs", "sys/search.fs", "sys/coreext.fs", "meta/i386-tconfig.fs", "meta/tconfig.fs", "meta/host-fina.fs", "meta/meta.fs", "meta/fina.fs"])
obj/kernel0.exe < obj/kernel/i386-dict1.fs > obj/kernel/dict1.S
```

**Comment by nbkolchin** [comment]
I've played with optimization flags:

- `-O0`: hangs on kernel0
- `-O1`: hangs on glosgen
- `-O2`: hangs on kernel0

**Comment by jacereda** [comment]
I've tried also with gcc 11.1.0 and works fine for me...

Looks like scons and make don't use the same flags, could you try also the make build?

**Comment by jacereda** [comment]
The problem is usually related to reordering, I've pushed a commit that marks the asm labels block as volatile, although I have doubts it'll make a difference.

**Comment by nbkolchin** [comment]
I've reproduced the problem under Ubuntu 18 with gcc 7.5.

Running with debug:

```
$ gdb obj/fina
GNU gdb (GDB) 11.1

Reading symbols from obj/fina...
(gdb) r
Starting program: obj/fina

Program received signal SIGSEGV, Segmentation fault.
internalTick (state=state@entry=0x7fffffffe4d0, throwval=<optimized out>) at kernel/prims.i:98
98                      tos = *(CELL*)tos;
(gdb) bt
#0  internalTick (state=state@entry=0x7fffffffe4d0, throwval=<optimized out>) at kernel/prims.i:98
#1  0x00005555555619a3 in FINA_InternalTick (throwval=<optimized out>, state=0x7fffffffe4d0) at kernel/finac.c:190
#2  Sys_Tick (state=state@entry=0x7fffffffe4d0) at kernel/sysposix.c:102
#3  0x0000555555561b51 in FINA_Tick (state=0x7fffffffe4d0) at kernel/finac.c:195
#4  main (argc=<optimized out>, argv=<optimized out>) at kernel/main.c:7
(gdb) p tos
Cannot access memory at address 0x80008
```

**Comment by nbkolchin** [comment]
Also, kernelX are able to execute simple "2 3 + . CR BYE". fina -- not

```
$ obj/kernel2 < hello.fth
5
$ obj/kernel1 < hello.fth
5
$ obj/kernel0 < hello.fth
5
$ obj/fina < hello.fth
^C
```

**Comment by nbkolchin** [comment]
I've added printing to FETCH implementation and got this:

```
$ obj/fina
FETCH: 0x55a63e4957b8
VALUE: 3E495C78
FETCH: 0x55a63e4957e0
VALUE: 3E4911C8
FETCH: 0x55a63e4911c0
VALUE: 63696405
FETCH: 0x55a63e4911b8
VALUE: 00000000
FETCH: 0x55a63e4911b0
VALUE: 3E4914B8
FETCH: 0x55a63e4911a8
VALUE: 3E491338
FETCH: 0x55a63e4911a0
VALUE: 3E4957A8
FETCH: 0x55a63e491198
VALUE: DEADBEEF
FETCH: 0x55a63e491190
VALUE: FEEDBABE
FETCH: 0x80008
```

**Comment by jacereda** [comment]
I reproduced it on Ubuntu, thanks.

**Comment by jacereda** [comment]
Looks like it was generating position-independent executables... Can you try again?

**Comment by jacereda** [comment]
I only fixed the Makefile build...

**Comment by nbkolchin** [comment]
It worked. Thanks.
